export const DETACH_AGENT_RELATIONSHIP_SKILL_NAME = "detach-agent-relationship";
export const DETACH_AGENT_RELATIONSHIP_SKILL_VERSION = "1.1.0";
export const DETACH_AGENT_RELATIONSHIP_SKILL_PROTOCOL_VERSION = "1.0.0";

