import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

const repoRoot = path.resolve(import.meta.dirname, "../../..");

const rootPackage = fs.readFileSync(path.join(repoRoot, "package.json"), "utf8");
const waitForServer = fs.readFileSync(path.join(repoRoot, "scripts/wait-for-server.mjs"), "utf8");
const settingsPanel = fs.readFileSync(path.join(repoRoot, "apps/web/src/features/settings/SettingsPanel.tsx"), "utf8");
const chatPanel = fs.readFileSync(path.join(repoRoot, "apps/web/src/features/chat/ChatPanel.tsx"), "utf8");
const connectionBar = fs.readFileSync(path.join(repoRoot, "apps/web/src/features/connection/ConnectionBar.tsx"), "utf8");
const app = fs.readFileSync(path.join(repoRoot, "apps/web/src/app/App.tsx"), "utf8");
const skillInstallPanel = fs.readFileSync(path.join(repoRoot, "apps/web/src/features/skills/SkillInstallPanel.tsx"), "utf8");
const terminalPanel = fs.readFileSync(path.join(repoRoot, "apps/web/src/features/terminal/TerminalPanel.tsx"), "utf8");
const toolQueuePanel = fs.readFileSync(path.join(repoRoot, "apps/web/src/features/tools/ToolQueuePanel.tsx"), "utf8");
const css = fs.readFileSync(path.join(repoRoot, "apps/web/src/styles/global.css"), "utf8");
const preview = fs.readFileSync(path.join(repoRoot, "docs/main-agent-advanced-settings-preview.html"), "utf8");

assert.match(settingsPanel, /高级配置/, "settings page should expose an advanced configuration entry");
assert.match(rootPackage, /wait-for-server\.mjs && pnpm --filter @detaches\/web dev/, "dev script should wait for the API server before starting Vite");
assert.match(waitForServer, /\/api\/health/, "wait-for-server should poll the local API health endpoint");
assert.match(settingsPanel, /Main Agent 服务信息/, "advanced settings should include Main Agent service information");
assert.match(settingsPanel, /Main Agent 回连本机/, "settings should include gateway-terminal callback settings");
assert.match(settingsPanel, /Agent Terminal Runtime/, "settings should show Agent Terminal Runtime session status");
assert.match(settingsPanel, /revokeAgentTerminalSession/, "settings should allow revoking Agent Terminal sessions");
assert.match(settingsPanel, /authorizeAgentTerminalSession/, "settings should allow authorizing pending Agent Terminal sessions");
assert.match(settingsPanel, /选择本机回连 IP/, "settings should expose callback IP selection");
assert.match(settingsPanel, /测试 gateway-terminal/, "settings should expose gateway-terminal test action");
assert.match(settingsPanel, /保存配置并重启 Detach Agent 后生效/, "settings should warn when selected callback IP needs a server restart");
assert.match(settingsPanel, /启用 ssh-terminal \/ reverse bridge/, "advanced settings should include the ssh-terminal bridge checkbox");
assert.match(settingsPanel, /localSshBridgeEnabled:\s*false/, "quick direct setup should disable local SSH bridge");

assert.match(chatPanel, /bootstrap-relationship-skill-check/, "ChatPanel should still support explicit relationship skill checks");
assert.match(chatPanel, /sendRelationshipSkillCheck/, "ChatPanel should centralize relationship skill check sending");
assert.match(chatPanel, /relationshipSkillCheckNonce/, "ChatPanel should allow New session to explicitly trigger skill checking");
assert.doesNotMatch(chatPanel, /sendRelationshipSkillCheck\("socket-open"\)/, "ChatPanel should not auto-check relationship skill on socket open");
assert.match(chatPanel, /includeLocalControlContext/, "ChatPanel should gate local-control prompt injection per message");
assert.match(chatPanel, /includeStagedFileContext/, "ChatPanel should gate staged-file prompt injection per message");
assert.match(chatPanel, /只发送文件说明/, "ChatPanel should support sending local staged files as description only");
assert.match(chatPanel, /Date\.now\(\)\.toString\(36\)/, "relationship skill checks should use unique idempotency keys");
assert.match(chatPanel, /isRelationshipSkillCheckMessage/, "ChatPanel should hide bootstrap skill check messages from visible chat");
assert.match(chatPanel, /PROMPT_PRESETS_STORAGE_KEY = "detaches\.promptPresets\.v1"/, "ChatPanel should persist prompt floating balls in localStorage");
assert.match(chatPanel, /PromptPresetRail/, "ChatPanel should render the prompt floating ball rail");
assert.match(chatPanel, /onDoubleClick/, "prompt floating balls should support double-click editing");
assert.match(chatPanel, /prompt-preset-mobile-toggle/, "prompt floating balls should expose a compact mobile toggle");
assert.match(chatPanel, /setDraft\(\(current\) => current\.trim\(\) \? `\$\{trimmed\}\\n\\n\$\{current\}` : trimmed\)/, "prompt presets should prepend without replacing the draft");
assert.match(chatPanel, /handleComposerDrop/, "ChatPanel should support dropping files onto the composer");
assert.match(chatPanel, /onNeedUpload\(event\.dataTransfer\.files\)/, "dropped files should use the existing upload flow");
assert.match(chatPanel, /onTerminalActivityChange\("running"\)/, "ChatPanel inline tool approvals should mark terminal commands as running");
assert.match(connectionBar, /relationship-skill-alert/, "ConnectionBar should render the relationship skill alert");
assert.match(connectionBar, /Relationship skill 未安装/, "ConnectionBar should show missing skill copy");
assert.match(connectionBar, /Relationship skill 需更新/, "ConnectionBar should show outdated skill copy");
assert.match(connectionBar, /更新 relationship skill/, "ConnectionBar should expose an update action for outdated skill");
assert.match(app, /relationshipSkillStatus/, "App should own relationship skill status state");
assert.match(app, /relationshipSkillInstalledVersion/, "App should keep the installed relationship skill version");
assert.match(app, /relationshipSkillRequiredVersion/, "App should keep the required relationship skill version");
assert.match(app, /localControlConsentByScope/, "App should track local-control consent per agent scope");
assert.match(app, /localControlRuntimeBySession/, "App should track local-control runtime per session");
assert.match(app, /relationshipSkillCheckNonce/, "New session should explicitly trigger the relationship skill check only when consent is enabled");
assert.match(app, /relationshipSkillPromptOpen/, "skill action should open the copyable prompt dialog");
assert.match(app, /RelationshipSkillPromptDialog/, "App should render a relationship skill prompt dialog");
assert.match(app, /fetchAgentTerminalSessions/, "App should poll Agent Terminal sessions for pending authorization");
assert.match(app, /AgentTerminalAuthorizationDialog/, "App should render a global Agent Terminal authorization dialog");
assert.match(app, /授权 gateway-terminal/, "Agent Terminal authorization dialog should expose an obvious approval action");
assert.match(app, /authorizeAgentTerminalSession/, "global Agent Terminal dialog should authorize pending sessions");
assert.match(app, /AgentTerminalToolApprovalDialog/, "App should render a global gateway-terminal command approval dialog");
assert.match(app, /isGatewayTerminalRequest/, "App should detect pending gateway-terminal tool requests globally");
assert.match(app, /批准执行/, "gateway-terminal command approval dialog should expose an obvious approve action");
assert.match(app, /approveToolRequest/, "global gateway-terminal dialog should approve pending tool requests");
assert.match(app, /terminalActivityBySession/, "App should track terminal activity state per session");
assert.match(app, /navigator\.clipboard\.writeText\(prompt\)/, "prompt dialog should copy the generated install/update prompt");
assert.match(app, /callbackHost/, "prompt dialog should include the current Detach Agent callback host when available");
assert.match(skillInstallPanel, /DETACH_AGENT_RELATIONSHIP_SKILL_VERSION/, "Skill install panel should use the shared required skill version");
assert.match(skillInstallPanel, /export const relationshipSkillInstallPrompt/, "Skill install panel should export the shared install/update prompt");
assert.match(skillInstallPanel, /DETACH_AGENT_SKILL_INSTALL_STATUS/, "Skill install panel should request parseable install status");
assert.match(skillInstallPanel, /detaches-agent-adapter\.mjs/, "Skill install prompt should also install the adapter CLI helper");
assert.match(terminalPanel, /activityState === "running"/, "TerminalPanel should show a running activity label");
assert.match(terminalPanel, /运行中/, "TerminalPanel should expose the running state copy");
assert.match(toolQueuePanel, /onTerminalActivityChange\?\.\("running"\)/, "ToolQueuePanel should mark terminal commands as running");
assert.doesNotMatch(toolQueuePanel, /onRevealTerminal\(\);/, "ToolQueuePanel should not auto-open the terminal after approving a command");

assert.match(css, /@keyframes skill-alert-pulse/, "CSS should include the orange breathing alert animation");
assert.match(css, /relationship-skill-prompt-dialog/, "CSS should style the relationship skill prompt dialog");
assert.match(css, /local-control-card/, "CSS should style the control-local enable panel");
assert.match(css, /prompt-preset-rail/, "CSS should style the prompt floating ball rail");
assert.match(css, /prompt-preset-list[\s\S]*overflow-y: auto/, "prompt floating ball list should support vertical scrolling");
assert.match(css, /prompt-preset-rail:not\(\.mobile-open\) \.prompt-preset-list/, "prompt floating ball rail should collapse on small screens");
assert.match(css, /prompt-preset-editor/, "CSS should style the prompt preset editor drawer");
assert.match(css, /composer\.drag-over/, "CSS should highlight the composer while dragging files");
assert.match(preview, /Main Agent 高级配置预览/, "static HTML preview should exist");
assert.match(preview, /Relationship skill 未安装/, "static HTML preview should show the missing skill reminder");

console.log("relationshipSkillUi: ok");
